// The three prebuilt story outlines, generated by scripts/gen-outlines.ts and
// validated against outlineSchema at generation time. Kept dependency-free so
// both server routes and client components can import them.

import type { StoryOutline } from "@/lib/storyEngine/types";
import noirJson from "./noir.json";
import fantasyJson from "./fantasy.json";
import starshipJson from "./starship.json";

export type PrebuiltStoryId = "noir" | "fantasy" | "starship";

export interface PrebuiltStory {
  id: PrebuiltStoryId;
  title: string;
  outline: StoryOutline;
}

// JSON imports widen enum-ish fields (qte.type, ending tone) to plain string,
// so a double cast is required; the gen script guarantees schema validity.
export const noir = noirJson as unknown as StoryOutline;
export const fantasy = fantasyJson as unknown as StoryOutline;
export const starship = starshipJson as unknown as StoryOutline;

export const prebuiltStories: PrebuiltStory[] = [
  { id: "noir", title: noir.title, outline: noir },
  { id: "fantasy", title: fantasy.title, outline: fantasy },
  { id: "starship", title: starship.title, outline: starship },
];

export const prebuiltById: Record<PrebuiltStoryId, StoryOutline> = {
  noir,
  fantasy,
  starship,
};
